### ISSUE TITLE
Support for later versions of AppleSingle archive format

### ISSUE THREAD

**Issue by fadden** [fadden/ciderpress#1]
[ imported from Andrew Roughan's feature request, https://sourceforge.net/p/ciderpress/feature-requests/3/ ]

I've been informed that Ciderpress does not handle the latest AppleSingle archive format. Apparently it was updated at some point after the release of GSHK.

While getting an Apple II artifact into a the latest AppleSingle archive format is probably not possible to do on a real Apple II, it has happened that Apple II files uploaded with a Mac can have this wrapper added.

Being able to remove this wrapper to get at the content within would be a nice to have addition to Ciderpress.

Test files: Binary file stored on Sourceforge that were uploaded with MacCVS
e.g.
http://marinetti.cvs.sourceforge.net/viewvc/marinetti/MOSP/Marinetti/LinkLayers/MACIP/MacIP.RES

Here's a description of Version 2
http://kaiser-edv.de/documents/AppleSingle_AppleDouble.pdf

**Comment by fadden** [comment]
AppleSingle is supported in v4.0.0d3.  Bit of a bumpy ride, but it's working.

**Comment by roughana** [comment]
Thank you very much.
