### ISSUE TITLE
Provide option to extract with conversion and keep original filenames

### ISSUE THREAD

**Issue by roughana** [fadden/ciderpress#10]
To facilitate moving source files out of an archive for use on Windows with Merlin32, I would like to have an option to extract files with conversion but to keep the filename unchanged.
Currently, Merlin source files are extracted with .TXT suffix. It is annoying to have to rename them.

**Comment by fadden** [comment]
This might be considered orthogonal to the feature request, but: would it make sense to avoid the rename by having Merlin32 accept both ".S" and ".S.TXT"?

I think the answer to that depends on the answer to the question, "what should happen when you double-click on the file in Windows?"  If you'd like it to open your text editor of choice, then having it end in ".TXT" would be reasonable.  If it's supposed to open an editor specific to ".S" files, then naming them ".S.TXT" makes less sense.

(I haven't used Merlin32.)

**Comment by roughana** [comment]
Thanks for the suggestion, but I don't think that's the right way to go.
Having the Merlin files as .S gives Windows the opportunity to associate a relevant app. I can imagine wanting different behavior for .S vs . txt.
Within a large project there are many references to .S files within Merlin source files that would need to be replaced. This would divide the source from its original heritage and co-mingling within a source code repository would be messy.
Regards
Andrew

**Comment by fadden** [comment]
Change pushed in 4.0.3-a3.
