### ISSUE TITLE
Can Disk Edit function be finished?

### ISSUE THREAD

**Issue by Keatah** [fadden/ciderpress#11]
Can Disk Edit function be completed?

**Comment by fadden** [comment]
It *can* be completed.  It's on a [long list](http://a2ciderpress.com/requested-features.htm) of features.  It's one of the more useful items, but it's also a non-trivial amount of work.  I don't anticipate it happening any time soon.

**Comment by fadden** [comment]
This will not be addressed in CiderPress.  With https://github.com/fadden/ciderpress2 you can do block/sector edits from the command line, though that's not terribly convenient.  It's on the list for the new GUI tool.

**Comment by Keatah** [comment]
This all looks very good! Love it!
