### ISSUE TITLE
CiderPress crashes when extracting files on WinXP

### ISSUE THREAD

**Issue by Keatah** [fadden/ciderpress#16]
Ciderpress CTD's when extracting files from a floppy image to the PC's hard disk, if you try canceling it while it is extracting.

I was working with a prodos image at the time, if that makes any difference..

**Comment by fadden** [comment]
What version of Windows are you using?  Are you on the latest version of CiderPress?

Is the floppy drive connected directly to the motherboard, or through a USB dongle?

Unfortunately the last couple generations of computers I built for myself didn't have floppy drives, so I'll need to sort that out before I can try to reproduce the crash.

**Comment by Keatah** [comment]
Latest version of CP on XP. I'll try win7 tomorrow when I'm back in town.

I was extracting files from a prodos image I got from ftp.asimov. By extracting I mean taking the files from the image and saving them to the My Documents folder on the PC. I didn't mention using a floppy or USB dongle. This is strictly from the downloaded image straight to a local folder.

**Comment by fadden** [comment]
Ah, I misunderstood.

I tried a quick test with CP on Win10, no crash.  WinXP is a bit of a special snowflake, so it could relate to that.  I'll need to fire up the XP test system.

**Comment by fadden** [comment]
Is this still a thing?  I never did reinstall XP.  (Should probably use virtual box...)

**Comment by fadden** [comment]
I tried installing WinXP in a VirtualBox VM.  I can't activate it, Windows Update no longer works... it's pretty clear that Microsoft wants it to go away.  According to one site, it's at 6% market share now, well behind 7/10 (but slightly ahead of Win8).

Since I have no chance of reproducing this, I doubt I can fix it.

**Comment by Keatah** [comment]
FWIW The error I get is:

MS Visual C++ Runtime Library

Assertion Failed!
Program..CiderPress.exe
File: Actions.cpp
Line: 1129

Expression pOutput->GetTextBuf()!=NULL
.
.
(Press Retry to debug the application - JIT must be enabled)

ABORT RETRY IGNORE
