### ISSUE TITLE
Assertion in diskimg5.dll; File: DiskImg.cpp; Line: 1158; Expression: fLength >= 0

### ISSUE THREAD

**Issue by mmmann** [fadden/ciderpress#22]
CiderPress is hitting an assertion failure. To reproduce: Use RAMFAST to format and create partitions on a SCSI hard drive. Note that the "hard drive" is a the "SCSI Hard Drive Emulator for retro computing" at http://www.codesrc.com/mediawiki/index.php?title=SCSI2SD, version 5b. This SCSI emulator on MicroSD works perfectly: all RAMFAST operations work, including formatting, creating partitions, reading and writing to the partitions, loading GS/OS 6.0.1, etc.

Unfortunately, when you bring the Hard Drive (the MicroSD card) to Windows 10 and ask CiderPress to open "a logical or physical volume," it triggers the assertion. You can see CiderPress's dialog printing the names of the partitions, one by one, very quickly, but it finally fails in a very non-elegant fashion:

Disk Sector Viewer and Volume Copier: C:\Src\CiderPress\diskimg\DiskImg.cpp, Line 1158, fLength >= 0 (sometimes line 1156).

If you ignore the assertion failure, CiderPress continues and lists the RAMFAST partitions. You can click [Copy to File] and copy the partition. UNFORTUNATELY, you cannot use [Load from File] (it's greyed out) as that's the most important function needed. I want to set up my SCSI hard drive, loading entire partitions as per http://www.whatisthe2gs.apple2.org.za/cffa2-card-review/. This would seem to be critical functionality. Please let me know how/if I can be of help to rectify this error. Thank you.

**Comment by fadden** [comment]
Do you have a disk image file that reproduces the problem that you can share? (You can drag & drop into the issue tracker.)

**Comment by mmmann** [comment]
Mr. McFadden, please contact me at my private Email address and share with me a physical mailing location. I will create twelve partitions on a small & cheap MicroSD and will mail it to you. I believe the best way to duplicate this problem is to have the MicroSD card plugged into your computer. My private Email is MAIL the-digit-four at WARE the-digit-four dot COM.

**Comment by fadden** [comment]
It's failing in an image analysis routine, so the results should be equivalent for physical media and disk image files.  If you can click through the assertions, select the outermost volume, and "copy to file", you should get a full-volume image.  Then, just open that file, and see if it fails in the same way.  If this works, it'll be quicker and easier than snail-mailing a micro SD.

One key thing to note: the "open volume" dialog has an "open as read-only" checkbox on it that is set by default.  This will prevent you from modifying the physical device, so the "load from file" button will be disabled.  Make sure that's unchecked.  (If that's annoying, go into Edit > Preferences > Disk Images, and un-check "default to read-only when opening volumes" to default to read-write access.)

FWIW, my e-mail is fadden at fadden.com.

**Comment by mmmann** [comment]
Mr. McFadden,

 

I have duplicated the errors, step by step, and have uploaded everything to: http://www.ware4.com/files/20171030-Assertion-Failure.zip.

 

Included are screen shots in the ScreenShots subdirectory, ordered by name for each step.

 

Yes, I failed to notice the "read-only" check box; that is user error.

 

Warmest regards,

 

Mike

**Comment by fadden** [comment]
I can reproduce the problem with that image.  It looks like CiderPress is unhappy with a partition called "Apple_FREE".  If you open the image file, hit Ctrl-I to get disk image info, and select that partition from the Sub-Volume pop-up, you'll get another assertion failure.

This appears to be a 64-bit math error... this:

    fLength = numBlocks * kBlockSize;

should have been this:

    fLength = (di_off_t)numBlocks * kBlockSize;

With that change, I can now see the 7GB Apple_FREE partition in the Disk Image Info dialog, and the assertion failures are gone.

Try this and see if it fixes things: https://github.com/fadden/ciderpress/releases/tag/v4.0.3-a1

**Comment by mmmann** [comment]
Mr. McFadden,

 

> Try this and see if it fixes things...

 

Yes! You nailed it. Bada-bing, bada-boom! The assertions are no longer triggering. Very cool. I was getting full functionality from the code, anyway, by ignoring the assertions. Thank God you compiled it in debug mode so that the assertions don't call unrecoverable_error_routine, or whatever that code point was in C++ that I can't remember.

 

> Tools > Disk Sector Viewer...

 

Yup. Every block has my original names on them, from block 1 to block 13.

 

> You can use Actions > Rename Volume to change the ProDOS volume name.

 

Ok, I figured it out. You have to open the entire volume (listing every file in every partition) and then Actions->Rename is available. It works. That's OK. But I'm a greedy, C++-programmer-turned-landlord with exorbitant and unrealistic expectations. :-) You still have the C++ source...still remember how to navigate around that old code? When you load a partition from a file, could there be a [x] checkbox that says "retain old partition name" or "use file system name" or "overwrite partition name," with a default that makes sense? The default would probably be to overwrite, since most people are using that option to "ghost" back an old partition, I would guess. Oh yeah, and the option could be sticky. Get on it, buddy. This is the highest priority to-do item in your life.

 

Anyway, all joking aside, I appreciate the help and the fast response. I've having a great time getting back to my Apple hobby. 

 

Warmest regards,

 

Mike

**Comment by fadden** [comment]
You're welcome!

I'll leave issue #23 open for the volume name thing. No promises. :-)
