### ISSUE TITLE
Allow saving of files in file viewer

### ISSUE THREAD

**Issue by silentwar-resident** [fadden/ciderpress#27]
allow to save files as converted like when you wanto save after converting pictures to windows , save as bmp or gif, jpg, etc  and other files like word, text, etc saved as rtf or text, etc

**Comment by fadden** [comment]
You can do this for many things by extracting them with "Configure for easy access in Windows" selected.  This will extract AWP as RTF and SHR as BMP.

The dialog doesn't let you choose the conversion mode, though, e.g. you can't select between color and B&W hi-res images.  You can copy & paste from the file viewer for individual files.

**Comment by silentwar-resident** [comment]
well it would be nice if they can save the converted file by a button when displaying converted file.

**Comment by silentwar-resident** [comment]
I mean like when you want to save the converted file in ciderpress itself  I don’t see a way to save it 

Sent from Mail for Windows 10

**Comment by fadden** [comment]
This will not be addressed in CiderPress.  However, your feedback prompted me to add an "export" button in the new file viewer; you can see it here: https://www.youtube.com/watch?v=_jDVdC6-eoA

(It doesn't actually function yet... it's a work in progress.)
