### ISSUE TITLE
create 32Mb image misses the last block

### ISSUE THREAD

**Issue by peterferrie** [fadden/ciderpress#35]
When I ask CiderPress 4.03 to create a 32Mb images, the file size is 0x1FFFE00 long, instead of 0x2000000 (but 16Mb images are 0x1000000 as expected).  That prevents ProDOS from using the last block in the image, and of concatenating images to produce a CFFA multi-partition image.

**Comment by fadden** [comment]
ProDOS can't use the last block -- the block count in the volume header is 16 bits.

The code in CreateImageDialog.cpp knows about the CFFA issue:

        } else if (fDiskFormatIdx == kFmtProDOS) {
            // Max is really 65535, but we allow 65536 for creation of volumes
            // that can be copied to CFFA cards.

If you select "32MB", you get a 65535*512 byte file.  If you click on "specify size" and enter 65536, it will create a 65535-block ProDOS volume in a 65536*512 byte file.

**Comment by peterferrie** [comment]
Okay, my mistake.  Thanks.
