### ISSUE TITLE
Wrong INSTR token in Apple III Business Basic

### ISSUE THREAD

**Issue by ERolfi** [fadden/ciderpress#38]
The INSTR token is erroneously converted to INSTR$ when viewing an Apple III Business Basic listing.

(Thank you for the great work on Ciderpress!)

**Comment by fadden** [comment]
Fixed in source tree.

@david-schmidt

**Comment by fadden** [comment]
Built in https://github.com/fadden/ciderpress/releases/tag/v4.0.4-d1
