### ISSUE TITLE
Possibility to convert into C#

### ISSUE THREAD

**Issue by wyatt-wong** [fadden/ciderpress#43]
Is there a chance to convert the code into C# ?

**Comment by fadden** [comment]
CiderPress is about 100K lines of C++, using the MFC UI toolkit.  You'd have to port the general stuff (straightforward) and rewrite the user interface (less straightforward).

You'd think a C# program would be *easier* to run on multiple platforms, but I haven't found a good cross-platform GUI solution for C#.  In theory you can use WinForms for the UI, and run the program on Linux and Mac OS under Mono, but I ran into some problems with that when writing SourceGen (some here: https://github.com/fadden/MonoBugs).  WinForms doesn't work all that well on any platform, including Windows, although CiderPress' UI requirements are straightforward enough that it might work fine.

If the UI is written with WPF, Linux and Mac OS X won't work.  If you write it with UWP, only Win10 works.

I haven't used C# native interfaces much, so I'm not sure how hard it would be to interface NufxLib and libhfs.  It might be necessary to write an interface layer.

People seem to have had success "wine-bottling" CiderPress for other platforms.  So far that seems the best approach.

**Comment by fadden** [comment]
The answer, it turns out, is "yes".  https://www.youtube.com/watch?v=_jDVdC6-eoA
