### ISSUE TITLE
A Bug exists in one of the transfer utilities to recurse down multiple files causing a segmentation fault.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [fadden/ciderpress#44]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by Zombie-Ryushu** [comment]
I am referring down multiple directories with a wildcard, using the makedisk utility.

**Comment by Zombie-Ryushu** [comment]
I am referring down multiple directories with a wildcard, using the makedisk utility.
The makedisk tool does not crash every time, only if the recursion of files are used.

**Comment by fadden** [comment]
I can reproduce the problem:

```
**412225** new/new[] failed and should throw an exception, but Valgrind
**412225**    cannot throw exceptions and so is aborting instead.  Sorry.
==412225==    at 0x483B3CC: ??? (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==412225==    by 0x483C5F5: operator new[](unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==412225==    by 0x1117E0: CopyFiles(DiskImgLib::DiskFS*, int, char**) (MakeDisk.cpp:153)
==412225==    by 0x111B81: Process(char const*, char const*, char const*, int, char**) (MakeDisk.cpp:303)
==412225==    by 0x11136B: main (MakeDisk.cpp:376)****
```

The issue occurs if you try to add a directory file, which `ftell` claims has a length of 0x7FFFFFFFFFFFFFFF.  `new[]` throws an exception, which MakeDisk doesn't handle.

The workaround is to use something like "find . -type f" to only find normal files.  The proper fix is to have MakeDisk ignore directories.  The simple fix is to add a 2GB file size test, which ought to be there anyway:

diff --git a/linux/MakeDisk.cpp b/linux/MakeDisk.cpp
index 38cb505..64c5af5 100644
--- a/linux/MakeDisk.cpp
+++ b/linux/MakeDisk.cpp
@@ -148,6 +148,12 @@ CopyFiles(DiskFS* pDiskFS, int argc, char** argv)
         }
 
         len = ftell(fp);
+        if (len >= 1L<<31) {    // 2GB
+            fprintf(stderr, "Warning: file '%s' too large, skipping\n", *argv);
+            fclose(fp);
+            argv++;
+            continue;
+        }
         rewind(fp);
 
         buf = new char[len];

It's a hack, but MakeDisk is about 70% hack, so I'm not too worried. :-)

**Comment by fadden** [comment]
I added an explicit test for "is it a regular file", as well as the length check.

**Comment by Zombie-Ryushu** [comment]
Cann a micro-release be produced to fix this bug?

**Comment by fadden** [comment]
Sure. This doesn't affect the Windows binary, so I don't need to make a new one of those. I take it you're downloading the tarball from the releases page?

**Comment by Zombie-Ryushu** [comment]
Yes I am. I build RPMs and DEBs

**Comment by neowinston** [comment]
Can I contribute somehow to make a diff?

**Comment by fadden** [comment]
https://github.com/fadden/ciderpress/releases/tag/v4.0.5-d1a
