### ISSUE TITLE
How to edit BASIC files

### ISSUE THREAD

**Issue by Nerun** [fadden/ciderpress#45]
I have a disk with a HELLO in BAS (#fc0801) format. I want to edit it (change the code). How to do that? I have exported to TXT file in windows, and tried to import after editing, but it fails to load in AppleWin.

HELLO.txt
```
10 HOME
20 PRINT "DISQUETE:"
30 PRINT "OPERADOR:"
40 VTAB(2): PRINT CHR$(4);"CATALOG"
50 NEW
60 END
```
Rename to _HELLO#fc0801_ (or _HELLO.BAS_)

Open CiderPress > Add Files > Select _HELLO#fc0801_

Select
* Use tags and guess type from extension
* Convert text files by file type

Click Accept

The result is corrupted (look 1st line) and don't load in AppleWin:
```
 18464 OME
20 PRINT "DISQUETE:"
30 PRINT "OPERADOR:"
40 VTAB(2): PRINT CHR$(4);"CATALOG"
50 NEW
60 END
```

**Comment by fadden** [comment]
Try this instead:

- extract BAS file from disk image to text file (just click "configure for easy access in Windows" when extracting)
- edit text file
- open disk image, and use Actions > Import BAS from text

The result of the tokenization process is reported, and you're given the opportunity to name the file.

The "convert text files by file type" is meant for CR/LF/CRLF end-of-line conversions.  It doesn't convert the text file back to tokenized BAS form.

In AppleWin you also have the option of using Shift+Insert to paste text.  So you could do a select-all in your text editor, go to AppleWin, then paste the entire source file in.  This is especially convenient if you've only edited a couple of lines.

**Comment by Nerun** [comment]
> Try this instead:
> 
> * extract BAS file from disk image to text file (just click "configure for easy access in Windows" when extracting)
> * edit text file
> * open disk image, and use Actions > Import BAS from text
> 
> The result of the tokenization process is reported, and you're given the opportunity to name the file.
> 
> The "convert text files by file type" is meant for CR/LF/CRLF end-of-line conversions. It doesn't convert the text file back to tokenized BAS form.

Works like a charm! Thank you so much!
 
> In AppleWin you also have the option of using Shift+Insert to paste text. So you could do a select-all in your text editor, go to AppleWin, then paste the entire source file in. This is especially convenient if you've only edited a couple of lines.

Didn't knowed that, thank you again!
