### ISSUE TITLE
Feature Request: Create subdirectory on ProDOS image

### ISSUE THREAD

**Issue by roughana** [fadden/ciderpress#50]
When adding files with copy paste from another source, I want to be able to add them into a subdirectory. How can I create a subdirectory within CP?

**Comment by fadden** [comment]
To create a directory, select an existing directory or the volume directory entry, and use Actions > Create Subdirectory to create a new subdirectory there.

When pasting files, you will be asked to specify which directory you want them to be added to.

You can use Edit > Paste Special to choose whether the incoming files retain their directory structure or are all placed directly in the target directory.

**Comment by roughana** [comment]
Sorry, I'm not sure how I missed that menu item.
