### ISSUE TITLE
ERROR: jump-to-label crosses variable initialization

### ISSUE THREAD

**Issue by akhepcat** [fadden/ciderpress#51]
in diskimg/ProDOS.cpp,  two variables are initialized in the middle of a jump, which is a no-no in c++

small patch to resolve that error.
[ProDOS.cpp.diff.txt](https://github.com/fadden/ciderpress/files/7123773/ProDOS.cpp.diff.txt)

**Comment by fadden** [comment]
Whoops, looks like I introduced that in a recent change (d39c6125).  gcc is not at all happy.

**Comment by fadden** [comment]
Should be happy now.  I fixed an unrelated warning while I was at it.

Thanks for the report!
