### ISSUE TITLE
Feature Request: Overwrite Volume in Partition Map

### ISSUE THREAD

**Issue by roughana** [fadden/ciderpress#54]
I have microSD card being used with SCSI2SD. It has Apple Partition Map of several partitions.
I want to completely replace the content of a partition with the latest HDV image of TotalReplay.
If I open two CP windows and select all content of TR window, ctrl-c, select partition destination in partition map and ctrl-p, I get 50 files copied before the volume directory is full. ie none of the subdirectories are being created in destination.
Is there another way to do what I want?

**Comment by fadden** [comment]
Two approaches:

 1. In Edit > Preferences, General tab, un-check "strip pathnames when pasting files".  Or, use Edit > Paste Special and select "keep full pathnames".
 2. Open the file with Tools > Volume Copier (open file).  Select the partition you want to replace, and use "load from file".  Overwrite the entire partition.  (If they're not exactly the same size, some complaints may ensue.)

**Comment by roughana** [comment]
Thanks for fast feedback. It can be done.
I opened the target microSD card partition with Tools -> Volume Copier (open volume)
Selected microSD card drive letter (unticking read-only) and selected the partition to overwrite.
Selected source image
Copy was done very quickly (compared with Apple II file copy).

Thank you!
