### ISSUE TITLE
Arm32/Arm64 release?

### ISSUE THREAD

**Issue by nl255** [fadden/ciderpress#58]
I am not sure how easy it would be but would it be possible to make an arm32 and arm64, or at least arm64, release as well as one for x86?  While the number of Windows 10/11 on ARM devices is limited doing so would also make ciderpress compatible with Android and devices like the Raspberry Pi since while wine works fine on those systems it does not do CPU emulation thus needs Windows/ARM executables rather than the normal x86/x64 ones.  Visual Studio should support compiling for ARM.

**Comment by fadden** [comment]
I could presumably hit a "build" button, but I have a number of concerns about it actually working, and no way to test it.  Looking around briefly, it appears that getting it to work would be something of an adventure, e.g. https://stackoverflow.com/q/62600092/294248 .  I'm reasonably sure there are some 32-bit dependencies in the CiderPress code; I have vague memories of pointers being stuffed into 32-bit MFC fields.

A better approach involves the use of .NET, which appears to be available for the Raspberry Pi as well as Windows / MacOS / Linux.  That still has the ARM testing issue but at least things are *expected* to work.

**Comment by fadden** [comment]
https://github.com/fadden/ciderpress2 should do the trick.  [This page](https://learn.microsoft.com/en-us/dotnet/iot/deployment) says .NET Core will run on the Raspberry Pi.  I'm not currently building ARM binaries, but that can be [worked around](https://github.com/fadden/CiderPress2/blob/main/Install.md#support-for-other-systems).
