### ISSUE TITLE
Feature Request: Support for adding AppleSingle files to a disk image

### ISSUE THREAD

**Issue by oliverschmidt** [fadden/ciderpress#61]
The cc65 toolchain creates by default AppleSingle files. They contain the ProDOS file type and aux type. This is especially useful for BIN files with an arbitrary load/start address. It seems desirable that those files can be added as-is to a disk image.

**Comment by fadden** [comment]
This will not be addressed in CiderPress.

It is, however, handled by https://github.com/fadden/ciderpress2, e.g. if you watch https://www.youtube.com/watch?v=_jDVdC6-eoA you'll see it adding the contents of an AppleSingle file to a ShrinkIt archive in a disk image in a ZIP archive.

CiderPress II supports adding files directly from AppleSingle, AppleDouble, NuLib2 preservation strings, and HFS+ files with resource forks and file types.  It also supports extracting to all of those.  Currently only the command-line tool works, however.

Note: AppleSingle files are expected to have a ".as" suffix.

**Comment by oliverschmidt** [comment]
1. Thanks for the quick and detailed response :-)
2. I simply were totally unaware of CiderPress II :-(

**Comment by fadden** [comment]
> I simply were totally unaware of CiderPress II

It only went up about 36 hours ago, so that's understandable. :-)

**Comment by oliverschmidt** [comment]
I see ;-)
