### ISSUE TITLE
Feature Request: Editing file data in the File Viewer.

### ISSUE THREAD

**Issue by lukazi-2020** [fadden/ciderpress#62]
Would it be possible to allow for editing of the file data in the File Viewer (as in a Hex/Sector editor)?

Many thanks for all your hard work in supporting the Apple II community.

**Comment by fadden** [comment]
Editing formatted data would be complicated, since most formats are converted from something else before they are displayed.  Editing it as raw hex could work though.

I plan to have a fully-functional sector editor in https://github.com/fadden/ciderpress2, but I hadn't thought about how to edit a file on disk (or in a file archive).  A file hex editor seem like it would be more useful than the Apple II approach, where you'd use a "follow file" feature.

How were you planning to use such a feature?

**Comment by lukazi-2020** [comment]
Thank-you for the quick reply. 

If you have plans for a sector editor in CiderPress2 then I'll just wait for that.

Most of the time it is small changes that I make. They are always in raw hex. For example changing the joystick routine from Atari Joyport to 4Play card. Also making changes to software when designing new hardware.

When I'm testing hardware sometimes that hardware is not implemented in an emulator. I'll use an emulator as much as I can but then I still need to do live testing. I'll make changes using hex editor to software on a dsk file. Copy the dsk file to the CF card (the dsk file does not sit on the CF filesystem but inside a harddrive po image file which sits on the CF filesystem). Boot the A2 using harddrive. Create a real floppy. Boot the A2 using real floppy. Debug hardware then start over by making more hex editor changes. It would be nice to be able to edit the dsk file which sits inside the harddrive po file.

**Comment by fadden** [comment]
I see.  I think what I have in mind for CiderPress II should work.

Technically, it works now, just not in a terribly convenient way.  For example, suppose you have a ShrinkIt disk image on a 32MB ProDOS volume:

```
$ cp2 v --depth=max hd.po
File: hd.po
Disk image (Unadorned) - 32.0MB ProDOS "NEWDISK", 32.0MB free
Type Auxtyp Modified          Length  Storage *Name
---- ------ --------------- -------- -------- ----------------------------------
NON  $0000  29-May-23 21:31     7846     8704  foo.sdk

  Catalog of "foo.sdk"
  Disk image (Unadorned, order=pdos/blk) - 140KB ProDOS "NEWDISK", 249 blocks free
  Type Auxtyp Modified          Length  Storage *Name
  ---- ------ --------------- -------- -------- ----------------------------------
  NON  $0000  29-May-23 21:31    11766    12288  README.md
```

You can read blocks from the compressed disk image by specifying `hd.po:foo.sdk` as the target on the command line:

```
$ cp2 read-block hd.po:foo.sdk 2
# block 2
000000: 00 00 03 00 f7 4e 45 57 44 49 53 4b 00 00 00 00  ....wNEWDISK....
000010: 00 00 00 00 00 00 bd f6 1f 15 00 00 bd f6 1f 15  ......=v....=v..
000020: 05 00 c3 27 0d 01 00 06 00 18 01 29 52 45 41 44  ..C'.......)READ
000030: 4d 45 2e 4d 44 00 00 00 00 00 00 00 08 00 18 00  ME.MD...........
000040: f6 2d 00 bd f6 1f 15 c0 80 c3 00 00 bd f6 1f 15  v-.=v..@.C..=v..
000050: 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
```

If you send the output to a file and edit the hex, you can write the edited form back with `cp2 write-block`.

This is less convenient than a GUI interface, but if you're iterating on a simple change it might work well enough.

**Comment by lukazi-2020** [comment]
I'll try it out. Thank you very much.

**Comment by fadden** [comment]
FWIW, the CiderPress II sector-edit GUI has been implemented.  Demo here: https://youtu.be/esEHP6Bo8GI?t=148

**Comment by lukazi-2020** [comment]
Hi Andy,

Thanks for the heads up. This will be a huge time saver for me. I will be able to do my changes now without having to resort to using multiple applications.

You are a legend.

Thank-you.
Alex.

________________________________
