### ISSUE TITLE
Handle reconstitution of resources that have been split by Mac OS X into ._<filename>

### ISSUE THREAD

**Issue by roughana** [fadden/ciderpress#8]
I received a source zip with files in it with resource forks split like this (AppleDouble format):
\TCZ.TermGS\TC.TERM.res
\TCZ.TermGS\._TC.TERM.res

I gather this was created when OS X copied the files to an SMB share.
Wikipedia says:
"OS X supports resource forks on Windows SMB shares by creating a hidden file in the same directory with the data fork file, with the characters "._" at the beginning of the file name."

I didn't realise they were split out because I had 'Do not show hidden files' option set in Windows Explorer. I discovered them when I added the entire folder to an SHK archive where they were visible.

My request is, when adding files that have been split in this way, reconstitute the resource fork on the file inside the SHK archive. I know Ciderpress has its own mechanism for splitting resource forks out and does reconstitute those, so this is hopefully a simple extension so support.

**Comment by fadden** [comment]
This will not be addressed in CiderPress.  See https://github.com/fadden/ciderpress2 instead.
